version: '3.3'

services:
  keycloak-db:
    image: mysql:8.0
    ports:
      - "33066:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_pass_123
    command: mysqld --sql_mode=""

  ct-kc-quarkus-iam:
    depends_on:
      - keycloak-db
    build:
      context: ../
      dockerfile: docker/Dockerfile
      args:
        DOCKER_BUILDKIT: 0
    ports:
      - 8888:8888
      - 8080:8080
      - 8443:8443
      - 9990:9990
    environment:
      KC_DB: mysql
      KC_DB_URL_HOST: keycloak-db
      KC_DB_URL_PORT: 3306
      KC_DB_SCHEMA: keycloak
      KC_DB_USERNAME: db_user
      KC_DB_PASSWORD: db_pass_123
      KC_DB_URL_PROPERTIES: ?useSSL=false&allowPublicKeyRetrieval=true

      # Uncomment when in production
      KEYCLOAK_ADMIN: keycloak.admin
      KEYCLOAK_ADMIN_PASSWORD: keycloak.admin

      KC_HOSTNAME_STRICT: false
      KC_HEALTH_ENABLED: true
      KC_METRICS_ENABLED: true

      DEBUG_PORT: 8888
      PROXY_ADDRESS_FORWARDING: 'true'

      KC_LOG_LEVEL: DEBUG
