FROM quay.io/keycloak/keycloak:21.0.1 as builder

# Enable health and metrics support
ENV KC_HEALTH_ENABLED=true
ENV KC_METRICS_ENABLED=true

# Configure a database vendor
ENV KC_DB=mysql

WORKDIR /opt/keycloak
# for demonstration purposes only, please make sure to use proper certificates in production instead
RUN keytool -genkeypair -storepass password -storetype PKCS12 -keyalg RSA -keysize 2048 -dname "CN=server" -alias server -ext "SAN:c=DNS:localhost,IP:127.0.0.1" -keystore conf/server.keystore

### Base

USER root

# Install the necessary packages

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        apt-transport-https ca-certificates curl jsvc unzip \
# git
        git \
# procps : for 'free' command
        procps \
# iptools-ping : for 'ping' command
#        iptools-ping \
# iproute2 : for 'ip' command
        iproute2 \
# java.lang.UnsatisfiedLinkError: /usr/local/openjdk-11/lib/libfontmanager.so: libfreetype.so.6: cannot open shared object file: No such file or directory
# java.lang.NoClassDefFoundError: Could not initialize class sun.awt.X11FontManager
# https://github.com/docker-library/openjdk/pull/235#issuecomment-424466077
        fontconfig libfreetype6 \
    && apt-get autoremove -y && rm -rf /var/lib/apt/lists/*

RUN groupadd -r keycloak -g 1000 \
    && useradd -u 1000 -r -g keycloak -m -d /opt/keycloak -s /sbin/nologin -c "Keycloak User" keycloak \
    && chown -R keycloak:keycloak /opt/keycloak \
    && chmod -R g+rw /opt/keycloak

### Configurations

ADD src/main/resources/tools /opt/keycloak/tools
RUN chmod +x /opt/keycloak/tools/*

ADD target/keycloak_providers /opt/keycloak/providers

RUN /opt/keycloak/bin/kc.sh build

FROM quay.io/keycloak/keycloak:21.0.1
COPY --from=builder /opt/keycloak/ /opt/keycloak/

### ------------------------- Start Keycloak ------------------------- ###

USER keycloak

# Ensure signals are forwarded to the JVM process correctly for graceful shutdown
ENV LAUNCH_JBOSS_IN_BACKGROUND true

# Expose Keycloak ports
EXPOSE 8080
EXPOSE 8443
EXPOSE 9990

ENTRYPOINT [ "/opt/keycloak/tools/docker-entrypoint.sh" ]

CMD ["-b", "0.0.0.0"]
